import { ROWS } from "./exercises-data.ts";

/**
 * The exercise catalogue.
 *
 * `exercises-data.ts` is generated by `scripts/build-exercises.mjs` from
 * hasaneyldrm/exercises-dataset and committed, so nothing fetches at build
 * time. Edit the script, not the array.
 *
 * It lives in `@mezo/api` rather than in the app because three callers need the
 * same list between them: the picker in the browser, Milo's search tool on the
 * server, and anything that has to turn a stored id back into a name.
 *
 * ponytail: the whole list reaches the client bundle, around 180 kB before
 * compression. That is the price of a picker that filters as you type without a
 * round trip per keystroke. If the bundle starts to matter, move
 * `searchExercises` behind a tRPC procedure and ship the browser only the rows
 * it is currently showing.
 */

export type Exercise = {
	id: string;
	name: string;
	/** One of `BODY_PARTS`. The dataset's own coarse grouping. */
	bodyPart: string;
	equipment: string;
	/** The primary muscle. */
	target: string;
	secondary: string[];
	/** Filename stem, shared by the still and the animation. */
	media: string;
};

/**
 * Pinned to a commit rather than a branch. The media is served straight to
 * users from here, so a dataset that reorganised itself upstream would break
 * every image at once with nothing in this repository having changed.
 *
 * The imagery is © Gym visual (https://gymvisual.com/), which is why it is
 * referenced rather than copied, and why anything that renders it says so.
 */
const MEDIA =
	"https://cdn.jsdelivr.net/gh/hasaneyldrm/exercises-dataset@7455efae41b330c265e7cd4b78dfa848e7ce5ebd";

/** Who the pictures belong to, for whatever screen shows one. */
export const MEDIA_ATTRIBUTION = {
	label: "Exercise imagery © Gym visual",
	href: "https://gymvisual.com/",
};

/** The still. Cheap, and what a list of forty rows should be showing. */
export const exerciseImage = (exercise: Exercise) =>
	`${MEDIA}/images/${exercise.media}.jpg`;

/** The animation. Around 90 kB each, so only ever on a screen that asked. */
export const exerciseGif = (exercise: Exercise) =>
	`${MEDIA}/videos/${exercise.media}.gif`;

export const EXERCISES: readonly Exercise[] = ROWS;

const BY_ID = new Map(ROWS.map((exercise) => [exercise.id, exercise]));

export const exerciseById = (id: string) => BY_ID.get(id);

export const BODY_PARTS: readonly string[] = [
	...new Set(ROWS.map((exercise) => exercise.bodyPart)),
].sort();

export const EQUIPMENT: readonly string[] = [
	...new Set(ROWS.map((exercise) => exercise.equipment)),
].sort();

/** How many rows one search may return. A picker renders all of them. */
const MAX_RESULTS = 200;

/** Runs of whitespace collapse, so "bench   press" still finds "bench press". */
const normalise = (value: string) =>
	value.trim().toLowerCase().replace(/\s+/g, " ");

/**
 * Substring matching on the name, plus exact matching on the two facets the
 * picker offers as chips.
 *
 * Deliberately not fuzzy. A typo that returns something plausible but wrong is
 * worse here than one that returns nothing, because whatever comes back gets
 * logged as the set somebody did.
 */
export function searchExercises(filter: {
	query?: string;
	bodyPart?: string;
	equipment?: string;
	limit?: number;
}): Exercise[] {
	const query = filter.query ? normalise(filter.query) : "";
	const limit = Math.min(filter.limit ?? MAX_RESULTS, MAX_RESULTS);

	const hits: Exercise[] = [];
	for (const exercise of ROWS) {
		if (filter.bodyPart && exercise.bodyPart !== filter.bodyPart) continue;
		if (filter.equipment && exercise.equipment !== filter.equipment) continue;
		if (query && !normalise(exercise.name).includes(query)) continue;
		hits.push(exercise);
		if (hits.length === limit) break;
	}
	return hits;
}
